name: light_im_sdk
description: A light im.
version: 0.1.0
repository: https://github.com/ggdream/light-im-sdk

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cross_file: ^0.3.3+4
  dio: ^5.2.1+1
  mime: ^1.0.4
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
